// libs/shared/ui/react/button/src/lib/components/button/button.tsx
import './button.module.css';
import { Button } from 'primereact/button';

export interface ButtonProps {
  label: string;
  iconType?: string;
  hasIcon: boolean;
  iconPosition?: 'left' | 'right' | 'top' | 'bottom';
}

const ReactButton = (props: ButtonProps) => {
  return (
    <Button
      label={props.label}
      icon={props.hasIcon ? props.iconType : ''}
      iconPos={props.hasIcon ? props.iconPosition : 'left'}
    />
  );
};

export default ReactButton;

// libs/shared/ui/angular/button/src/lib/components/button/button.component.ts
import { Component, ChangeDetectionStrategy, Input } from '@angular/core';

@Component({
  selector: 'cha-ang-button',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ButtonComponent {
  @Input() label = '';
  @Input() type = 'button';
  @Input() hasIcon = false;
  @Input() iconType = '';
  @Input() iconPosition: 'left' | 'right' | 'top' | 'bottom' = 'left';
}

<button
  pButton
  [label]="label"
  [type]="type"
  [icon]="hasIcon ? iconType : ''"
  [iconPos]="hasIcon ? iconPosition : 'left'"
></button>
